export const site = {
  name: 'Olga Kuznetsova',
  role: 'Frontend-developer',
  intro: 'Разработка современных веб-интерфейсов и веб-приложений',
  email: 'ms.olgasmith.jj@mail.ru',
  github: 'https://github.com/olgaAsmith',
  telegram: 'https://t.me/ukolaa',
  url: 'https://olgaasmith.github.io/profile',
  skills: [
    'React',
    'Next.js',
    'TypeScript',
    'HTML',
    'CSS',
    'JavaScript',
    'SASS/SCSS',
    'Git',
    'API',
    'Figma',
    'GSAP',
    'CSS Animations',
    'Tailwind',
    'BEM',
    'Zustand',
    'Wordpress',
  ],
};
